# Generated by Django 5.2.8 on 2025-11-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo'),
        ),
    ]
